In [1]:
import pandas as pd
from scripts.table_builder import build_table1

In [2]:
df = pd.read_csv("./data/heart_failure_clinical_records_dataset.csv")
df.head()

,age,anaemia,creatinine_phosphokinase,diabetes,ejection_fraction,high_blood_pressure,platelets,serum_creatinine,serum_sodium,sex,smoking,time,DEATH_EVENT
0,75.0,0,582,0,20,1,265000.00,1.9,130,1,0,4,1
1,55.0,0,7861,0,38,0,263358.03,1.1,136,1,0,6,1
2,65.0,0,146,0,20,0,162000.00,1.3,129,1,1,7,1
3,50.0,1,111,0,20,0,210000.00,1.9,137,1,0,7,1
4,65.0,1,160,1,20,0,327000.00,2.7,116,0,0,8,1

In [3]:



continuous_cols = ["age", "creatinine_phosphokinase", "ejection_fraction","platelets", "serum_creatinine", "serum_sodium", "time"]
categorical_cols = ["sex", "anaemia", "diabetes", "high_blood_pressure", "smoking"]

table1, details = build_table1(
    df=df,
    group_col="DEATH_EVENT", # status
    continuous_cols=continuous_cols,
    categorical_cols=categorical_cols,
    alpha=0.05,
)

display(table1)

                                       Type            Test Statistic  \
Variable                 Level
age                              continuous  Mann-Whitney U   12367.0
creatinine_phosphokinase         continuous  Mann-Whitney U   10028.0
ejection_fraction                continuous  Mann-Whitney U    6311.5
platelets                        continuous  Mann-Whitney U    9187.5
serum_creatinine                 continuous  Mann-Whitney U   14190.0
serum_sodium                     continuous  Mann-Whitney U    7226.5
time                             continuous  Mann-Whitney U    3199.5
sex                      1      categorical      Chi-square  0.005571
                         0
anaemia                  0      categorical      Chi-square  1.313126
                         1
diabetes                 0      categorical      Chi-square  0.001129
                         1
high_blood_pressure      1      categorical      Chi-square  1.882681
                         0
smoking                  0      categorical      Chi-square  0.047644
                         1

                                 p_value Note  \
Variable                 Level
age                             0.000167
creatinine_phosphokinase         0.68404
ejection_fraction               0.000001
platelets                       0.425559
serum_creatinine                     0.0
serum_sodium                    0.000293
time                                 0.0
sex                      1      0.940503
                         0
anaemia                  0      0.251829
                         1
diabetes                 0        0.9732
                         1
high_blood_pressure      1       0.17003
                         0
smoking                  0      0.827215
                         1

                                                               1  \
Variable                 Level
age                                         65.00 [55.00, 75.00]
creatinine_phosphokinase                 259.00 [128.75, 582.00]
ejection_fraction                           30.00 [25.00, 38.00]
platelets                       258500.00 [197500.00, 311000.00]
serum_creatinine                               1.30 [1.08, 1.90]
serum_sodium                             135.50 [133.00, 138.25]
time                                       44.50 [25.50, 102.25]
sex                      1                         62/96 (64.6%)
                         0                         34/96 (35.4%)
anaemia                  0                         50/96 (52.1%)
                         1                         46/96 (47.9%)
diabetes                 0                         56/96 (58.3%)
                         1                         40/96 (41.7%)
high_blood_pressure      1                         39/96 (40.6%)
                         0                         57/96 (59.4%)
smoking                  0                         66/96 (68.8%)
                         1                         30/96 (31.2%)

                                                               0
Variable                 Level
age                                         60.00 [50.00, 65.00]
creatinine_phosphokinase                 245.00 [109.00, 582.00]
ejection_fraction                           38.00 [35.00, 45.00]
platelets                       263000.00 [219500.00, 302000.00]
serum_creatinine                               1.00 [0.90, 1.20]
serum_sodium                             137.00 [135.50, 140.00]
time                                      172.00 [95.00, 213.00]
sex                      1                       132/203 (65.0%)
                         0                        71/203 (35.0%)
anaemia                  0                       120/203 (59.1%)
                         1                        83/203 (40.9%)
diabetes                 0                       118/203 (58.1%)
                         1                        85/203 (41.9%)
high_blood_pressure      1                        66/203 (32.5%)
                         0                       137/203 (67.5%)
smoking                  0                       137/203 (67.5%)
                         1                        66/203 (32.5%)

In [6]:
table1.to_csv("results.csv")